### ISSUE TITLE
Personal Information Leak

### ISSUE THREAD

**Issue by kshashank231** [isopropylcyanide/Mess-App-Manager-Version#1]
Hey, looks like u put all the details of students out open in this app.. see for file mess-munshi.json. please consider removing it. Thank you. @isopropylcyanide

**Comment by isopropylcyanide** [comment]
Good catch. [Removed](https://github.com/isopropylcyanide/Mess-App-Manager-Version/commit/a5ab0e3fccc809a10b9c4d3203df8b31db93ff90) :)
